In [8]:
import torch
import torch.nn as nn

## Tensors

### Convert List to Tensor

In [2]:
temperatures = [[72, 75, 78], [70, 73, 76]]

# Create a tensor from temperatures
temp_tensor = torch.tensor(temperatures)

print(temp_tensor)

tensor([[72, 75, 78],
        [70, 73, 76]])


### Checking and Adding Tensors

In [7]:
adjustment = torch.tensor([[2, 2, 2], [2, 2, 2]])

# Display the shape of the adjustment tensor
print("Adjustment shape:", adjustment.shape)

# Display the type of the adjustment tensor
print("Adjustment type:", adjustment.dtype)

print("Temperatures shape:", temp_tensor.shape)
print("Temperatures type:", temp_tensor.dtype)

# Add the temperatures and adjustment tensors
corrected_temperatures = temp_tensor + adjustment
print("Corrected temperatures:", corrected_temperatures)

Adjustment shape: torch.Size([2, 3])
Adjustment type: torch.int64
Temperatures shape: torch.Size([2, 3])
Temperatures type: torch.int64
Corrected temperatures: tensor([[74, 77, 80],
        [72, 75, 78]])


## Neural Networks and Layers

### Linear Layer

In [11]:
# Create a Linear layer that takes 3 features as input and returns 2 outputs.

input_tensor = torch.tensor([[0.3471, 0.4547, -0.2356]])

# Create a Linear layer
linear_layer = nn.Linear(
                         in_features=3, 
                         out_features=2
                         )
# Pass input_tensor through the linear layer
output = linear_layer(input_tensor)

print(output)

tensor([[-0.0656, -0.1995]], grad_fn=<AddmmBackward0>)


### Weights

## Hidden Layers

### First NN

In [14]:
# implement a small neural network containing two linear layers in sequence.
input_tensor = torch.Tensor([[2, 3, 6, 7, 9, 3, 2, 1]])

# Create a container for stacking linear layers
model = nn.Sequential(
    nn.Linear(8,4),
    nn.Linear(4,1)
)

output = model(input_tensor)
print(output)

tensor([[0.8126]], grad_fn=<AddmmBackward0>)


### Counting the number of parameters

In [15]:
# Use .numel() to confirm your manual calculation by iterating through the model's parameters to updating the total variable.
model = nn.Sequential(nn.Linear(9, 4),
                      nn.Linear(4, 2),
                      nn.Linear(2, 1))

total = 0

# Calculate the number of parameters in the model
for parameter in model.parameters():
  total += parameter.numel()
  
print(f"The number of parameters in the model is {total}")

The number of parameters in the model is 53
